name: Echo Action
description: "List file in workspace"
inputs:
  workspace-path:
    description: "Path of workspace"
    required: false
    default: ""
outputs:
  results-file:
    description: "Path of results file"
jobs:
  Echo-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls -lah .
          # Unrecognized named-value: 'github'.
          # ls ${{ github.workspace }}