name: List Files
description: "List file in workspace"

runs:
  steps:
    - name: List files in the repository    
      run: |
        ls -lah .
      shell: bash

# memo: Error
# Unrecognized named-value: 'github'.
# ls ${{ github.workspace }}
