name: List Files
description: "List file in workspace"

runs:
  usings: "composite"
  steps:
    - name: List files in the repository
      shell: bash
      run: |
        ls -lah .

# memo: Error
# Unrecognized named-value: 'github'.
# ls ${{ github.workspace }}
