name: List Files
description: "List file in workspace"
runs:
  steps:
    # Unrecognized named-value: 'github'.
    # ls ${{ github.workspace }}
    - name: List files in the repository
      shell: bash
      run: |
        ls -lah .

