name: List Files
description: "List file in workspace"
runs:
  steps:
    - id: list-files
      name: List files in the repository
      shell: bash
      run: |
        ls -lah .

# memo: Error
# Unrecognized named-value: 'github'.
# ls ${{ github.workspace }}
