name: Call Action
on:
  push:
    branches: main
jobs:
  Call-Echo-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: ls .

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Call List Files Action
        id: list-file
        uses: ./.github/actions/list-files
        with:
          who-to-greet: 'Nobody'

      - name: Show output
        run: echo random-number ${{ steps.list-file.outputs.random-number }}
        shell: bash
