name: Call Action
on:
  push:
    branches: main
jobs:
  Call-Echo-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
#      - run: ls .

#      - name: List files in the repository
#        run: |
#          ls ${{ github.workspace }}
      
      - name: Call Echo Action
        uses: ./.github/actions/list-files

#      - name: Call Echo Action with Composite
#        id: echo-composite
#        uses: ./.github/actions/list-files-with-composite
#        with:
#          who-to-greet: 'Nobody'

#      - name: Show output
#        run: echo random-number ${{ steps.echo-composite.outputs.random-number }}
#        shell: bash
