name: Call Action
on:
  push:
    branches: main
jobs:
  Call-Echo-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Call Echo Action
        uses: ./.github/actions/list-files-action
