name: Cleanup Old Workflow
on: 
  schedule: 
    - cron: '* * * * *'
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh api ${{ github.repository }}/actions/runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
