name: Report remaining open issues
on: 
  schedule: 
    - cron: '*/5 * * * *'
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh api ${{ github.repository }}/actions/runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          