name: Cleanup Old Workflow

on:
  workflow_dispatch:
  
  schedule: 
    - cron: "*/5 * * * *"
    
jobs:
  Cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "/repos/${{ github.repository }}/actions/runs"

      - name: Show Workflow
        run: gh api /repos/${{ github.repository }}/actions/runs | jq '.workflow_runs[] | .id' | sort | head -n -10 | wc -l
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
