# https://docs.github.com/en/rest/actions/workflow-runs#list-workflow-runs-for-a-repository
name: Cleanup Old Workflow

on:
  workflow_dispatch:
  
  schedule: 
    - cron: "0 0 * * *"
    
jobs:
  Cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "/repos/${{ github.repository }}/actions/runs"

#      - name: Show Workflow ID
#        run: gh api /repos/${{ github.repository }}/actions/runs | jq '.workflow_runs[] | .id' | sort | head -n -10
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Echo Delete Workflow ID
#        run: gh api /repos/${{ github.repository }}/actions/runs |  jq '.workflow_runs[] | .id' | sort | head -n -20 | xargs -I{} echo "gh api -X DELETE /repos/${{ github.repository }}/actions/runs/{}"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Delete Workflow ID
        run: gh api /repos/${{ github.repository }}/actions/runs |  jq '.workflow_runs[] | .id' | sort | head -n -20 | xargs -I{} gh api -X DELETE /repos/${{ github.repository }}/actions/runs/{}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
