# https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers

name: Container Service Example
on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    services:
      mysql-db:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: sample_db
          MYSQL_USER: sample
          MYSQL_PASSWORD: sample_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # - name: Show Docker containers
      #  run: docker ps -a

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            cd ./javascript
            yarn install

      - name: Connect to MySQL
        env:
          MYSQL_HOST: mysql-db
          MYSQL_PORT: 3306
          MYSQL_USER: sample
          MYSQL_PASSWORD: sample_password
          MYSQL_DB: sample_db
        run: |
            cd ./javascript
            yarn serve
